from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[2]
ENV_PATH = PROJECT_ROOT / "src" / ".env"
DEFAULT_STORY_PATH = PROJECT_ROOT / "data" / "examples" / "story.txt"
MODEL_CACHE_DIR = PROJECT_ROOT / ".hf-cache" / "hub"
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_PATH = DATA_DIR / "raw" / "news-sample.jsonl"
DISTILLATION_OUTPUT_PATH = DATA_DIR / "datasets" / "sft.jsonl"
FINETUNING_FORMAT_SHUFFLE_SEED = 101
FINETUNING_TRAIN_SAMPLE_SIZE = 2700
LLAMA_FACTORY_DATA_DIR = DATA_DIR / "datasets" / "llama_factory"
LLAMA_FACTORY_REPOSITORY_DIR = PROJECT_ROOT / "LLaMA-Factory"
LLAMA_FACTORY_TRAIN_PATH = LLAMA_FACTORY_DATA_DIR / "train.json"
LLAMA_FACTORY_VALIDATION_PATH = LLAMA_FACTORY_DATA_DIR / "val.json"
LLAMA_FACTORY_TRAIN_DATASET_NAME = "news_finetune_train"
LLAMA_FACTORY_VALIDATION_DATASET_NAME = "news_finetune_val"
TRAINING_CONFIG_FILENAME = "news_finetune.yaml"
TRAINING_CONFIG_SOURCE_PATH = (
    PROJECT_ROOT / "configs" / "llamafactory" / TRAINING_CONFIG_FILENAME
)
FINETUNED_MODEL_RELATIVE_DIR = (
    Path("outputs") / "models" / "news-finetune"
)
FINETUNED_MODEL_DIR = PROJECT_ROOT / FINETUNED_MODEL_RELATIVE_DIR
BENCHMARK_SAMPLE_COUNT = 30
BENCHMARK_RANDOM_SEED = 101
BENCHMARK_MIN_PROMPT_CHARS = 150
BENCHMARK_MAX_PROMPT_CHARS = 200
BENCHMARK_OUTPUT_DIR = PROJECT_ROOT / "outputs" / "Evaluation"

QWEN_MODEL_ID = "Qwen/Qwen2.5-1.5B-Instruct"

VLLM_MODEL_ID = "news-lora"
VLLM_BASE_MODEL_ID = QWEN_MODEL_ID
VLLM_ADAPTER_DIR = FINETUNED_MODEL_DIR
VLLM_API_BASE_URL = "http://localhost:8000/v1"
VLLM_LOCAL_API_KEY = "local-vllm"
VLLM_MAX_TOKENS = 1000
VLLM_TEMPERATURE = 0.3
VLLM_REQUEST_TIMEOUT_SECONDS = 180.0
VLLM_READINESS_ATTEMPTS = 120
VLLM_READINESS_INTERVAL_SECONDS = 5.0
VLLM_LOAD_TEST_OUTPUT_DIR = PROJECT_ROOT / "outputs" / "LoadTesting"
VLLM_LOAD_TEST_JSONL_PATH = VLLM_LOAD_TEST_OUTPUT_DIR / "vllm-tokens.jsonl"
VLLM_LOAD_TEST_HTML_PATH = VLLM_LOAD_TEST_OUTPUT_DIR / "locust-results.html"
VLLM_LOAD_TEST_SUMMARY_TEXT_PATH = VLLM_LOAD_TEST_OUTPUT_DIR / "token-summary.txt"
VLLM_LOAD_TEST_SUMMARY_JSON_PATH = VLLM_LOAD_TEST_OUTPUT_DIR / "token-summary.json"
VLLM_LOAD_TEST_FAKER_LOCALE = "ar_SA"
VLLM_LOAD_TEST_RANDOM_SEED = 101
VLLM_LOAD_TEST_MIN_PROMPT_CHARS = 150
VLLM_LOAD_TEST_MAX_PROMPT_CHARS = 200
VLLM_LOAD_TEST_MAX_TOKENS = 512
VLLM_LOAD_TEST_TEMPERATURE = 0.3

QWEN_MAX_NEW_TOKENS = 1024
QWEN_DO_SAMPLE = False
QWEN_TEMPERATURE = None
QWEN_TOP_P = None
QWEN_TOP_K = None
QWEN_CUDA_DEVICE = "cuda"
QWEN_CPU_DEVICE = "cpu"
QWEN_CUDA_DTYPE = "float16"
QWEN_CPU_DTYPE = "float32"
QWEN_DEVICE_MAP = "auto"

GEMINI_MODEL_ID = "gemini-3.1-flash-lite"
GEMINI_MAX_OUTPUT_TOKENS = 1024
GEMINI_TEMPERATURE = 0.2
GEMINI_RESPONSE_MIME_TYPE = "application/json"

OPENAI_MODEL_ID = "gpt-4o-mini"
OPENAI_TEMPERATURE = 0.2
OPENAI_RESPONSE_FORMAT = {"type": "json_object"}

DISTILLATION_TEACHER_MODEL_ID = "o4-mini"
DISTILLATION_RESPONSE_FORMAT = {"type": "json_object"}
DISTILLATION_SHUFFLE_SEED = 101
DISTILLATION_REPORT_INTERVAL = 10
O4_MINI_INPUT_PRICE_PER_1M_TOKENS = 1.10
O4_MINI_CACHED_INPUT_PRICE_PER_1M_TOKENS = 0.275
O4_MINI_OUTPUT_PRICE_PER_1M_TOKENS = 4.40

# Backward-compatible name used by existing training code.
BASE_MODEL_ID = QWEN_MODEL_ID


def qwen_generation_kwargs() -> dict[str, Any]:
    return {
        "max_new_tokens": QWEN_MAX_NEW_TOKENS,
        "do_sample": QWEN_DO_SAMPLE,
        "temperature": QWEN_TEMPERATURE,
        "top_p": QWEN_TOP_P,
        "top_k": QWEN_TOP_K,
    }


# Backward-compatible helper used by the existing Qwen evaluator.
generation_kwargs = qwen_generation_kwargs
